[package]
name = "wasmtime-component-test"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.48.0"
fern-sdk = {path = "../../fern-sdk"}
env_logger = "0.11.8"
tokio = {version = "1.48.0", features = ["sync"]}
